/*
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GenerateMeGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GenerateMeProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.GenerateMeProgram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBusinessNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBusinessNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBusinessNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cBusinessNameAssignment_1.eContents().get(0);
		private final Assignment cConfigAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConfigConfigParserRuleCall_2_0 = (RuleCall)cConfigAssignment_2.eContents().get(0);
		private final Assignment cHomePageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHomePageHomePageParserRuleCall_3_0 = (RuleCall)cHomePageAssignment_3.eContents().get(0);
		private final Assignment cPagesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPagesPagesParserRuleCall_4_0 = (RuleCall)cPagesAssignment_4.eContents().get(0);
		
		//GenerateMeProgram:
		//	'BusinessName' businessName=STRING
		//	config=Config
		//	homePage=HomePage
		//	pages+=Pages*;
		@Override public ParserRule getRule() { return rule; }
		
		//'BusinessName' businessName=STRING config=Config homePage=HomePage pages+=Pages*
		public Group getGroup() { return cGroup; }
		
		//'BusinessName'
		public Keyword getBusinessNameKeyword_0() { return cBusinessNameKeyword_0; }
		
		//businessName=STRING
		public Assignment getBusinessNameAssignment_1() { return cBusinessNameAssignment_1; }
		
		//STRING
		public RuleCall getBusinessNameSTRINGTerminalRuleCall_1_0() { return cBusinessNameSTRINGTerminalRuleCall_1_0; }
		
		//config=Config
		public Assignment getConfigAssignment_2() { return cConfigAssignment_2; }
		
		//Config
		public RuleCall getConfigConfigParserRuleCall_2_0() { return cConfigConfigParserRuleCall_2_0; }
		
		//homePage=HomePage
		public Assignment getHomePageAssignment_3() { return cHomePageAssignment_3; }
		
		//HomePage
		public RuleCall getHomePageHomePageParserRuleCall_3_0() { return cHomePageHomePageParserRuleCall_3_0; }
		
		//pages+=Pages*
		public Assignment getPagesAssignment_4() { return cPagesAssignment_4; }
		
		//Pages
		public RuleCall getPagesPagesParserRuleCall_4_0() { return cPagesPagesParserRuleCall_4_0; }
	}
	public class ConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.Config");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSenderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSenderAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSenderSTRINGTerminalRuleCall_1_0 = (RuleCall)cSenderAssignment_1.eContents().get(0);
		private final Keyword cAuthorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAuthorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAuthorSTRINGTerminalRuleCall_3_0 = (RuleCall)cAuthorAssignment_3.eContents().get(0);
		
		//Config:
		//	'Sender' sender=STRING
		//	'Author' author=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Sender' sender=STRING 'Author' author=STRING
		public Group getGroup() { return cGroup; }
		
		//'Sender'
		public Keyword getSenderKeyword_0() { return cSenderKeyword_0; }
		
		//sender=STRING
		public Assignment getSenderAssignment_1() { return cSenderAssignment_1; }
		
		//STRING
		public RuleCall getSenderSTRINGTerminalRuleCall_1_0() { return cSenderSTRINGTerminalRuleCall_1_0; }
		
		//'Author'
		public Keyword getAuthorKeyword_2() { return cAuthorKeyword_2; }
		
		//author=STRING
		public Assignment getAuthorAssignment_3() { return cAuthorAssignment_3; }
		
		//STRING
		public RuleCall getAuthorSTRINGTerminalRuleCall_3_0() { return cAuthorSTRINGTerminalRuleCall_3_0; }
	}
	public class HomePageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.HomePage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIntroductionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIntroductionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIntroductionSTRINGTerminalRuleCall_1_0 = (RuleCall)cIntroductionAssignment_1.eContents().get(0);
		
		//HomePage:
		//	'Introduction' Introduction=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Introduction' Introduction=STRING
		public Group getGroup() { return cGroup; }
		
		//'Introduction'
		public Keyword getIntroductionKeyword_0() { return cIntroductionKeyword_0; }
		
		//Introduction=STRING
		public Assignment getIntroductionAssignment_1() { return cIntroductionAssignment_1; }
		
		//STRING
		public RuleCall getIntroductionSTRINGTerminalRuleCall_1_0() { return cIntroductionSTRINGTerminalRuleCall_1_0; }
	}
	public class PagesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.Pages");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cContentPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGalleryPageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cContactUsPageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Pages:
		//	ContentPage | GalleryPage | ContactUsPage;
		@Override public ParserRule getRule() { return rule; }
		
		//ContentPage | GalleryPage | ContactUsPage
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ContentPage
		public RuleCall getContentPageParserRuleCall_0() { return cContentPageParserRuleCall_0; }
		
		//GalleryPage
		public RuleCall getGalleryPageParserRuleCall_1() { return cGalleryPageParserRuleCall_1; }
		
		//ContactUsPage
		public RuleCall getContactUsPageParserRuleCall_2() { return cContactUsPageParserRuleCall_2; }
	}
	public class ContentPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.ContentPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContentPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPageHeaderKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cContentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cContentSTRINGTerminalRuleCall_4_0 = (RuleCall)cContentAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ContentPage:
		//	'ContentPage' name=ID '{'
		//	'PageHeader' content=STRING
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ContentPage' name=ID '{' 'PageHeader' content=STRING '}'
		public Group getGroup() { return cGroup; }
		
		//'ContentPage'
		public Keyword getContentPageKeyword_0() { return cContentPageKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'PageHeader'
		public Keyword getPageHeaderKeyword_3() { return cPageHeaderKeyword_3; }
		
		//content=STRING
		public Assignment getContentAssignment_4() { return cContentAssignment_4; }
		
		//STRING
		public RuleCall getContentSTRINGTerminalRuleCall_4_0() { return cContentSTRINGTerminalRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ContactUsPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.ContactUsPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContactUsPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPageHeaderKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cContentAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cContentSTRINGTerminalRuleCall_4_0 = (RuleCall)cContentAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ContactUsPage:
		//	'ContactUsPage' name=ID '{'
		//	'PageHeader' content=STRING
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ContactUsPage' name=ID '{' 'PageHeader' content=STRING '}'
		public Group getGroup() { return cGroup; }
		
		//'ContactUsPage'
		public Keyword getContactUsPageKeyword_0() { return cContactUsPageKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'PageHeader'
		public Keyword getPageHeaderKeyword_3() { return cPageHeaderKeyword_3; }
		
		//content=STRING
		public Assignment getContentAssignment_4() { return cContentAssignment_4; }
		
		//STRING
		public RuleCall getContentSTRINGTerminalRuleCall_4_0() { return cContentSTRINGTerminalRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class GalleryPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.GalleryPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGalleryPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPhotosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPhotosPhotoParserRuleCall_3_0 = (RuleCall)cPhotosAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//GalleryPage:
		//	'GalleryPage' name=ID '{'
		//	photos+=Photo
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GalleryPage' name=ID '{' photos+=Photo '}'
		public Group getGroup() { return cGroup; }
		
		//'GalleryPage'
		public Keyword getGalleryPageKeyword_0() { return cGalleryPageKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//photos+=Photo
		public Assignment getPhotosAssignment_3() { return cPhotosAssignment_3; }
		
		//Photo
		public RuleCall getPhotosPhotoParserRuleCall_3_0() { return cPhotosPhotoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PhotoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.juliusz.generateme.GenerateMe.Photo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPhotoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPhotoTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPhotoTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cPhotoTitleAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPhotoDescriptionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cPhotoFileNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFileNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFileNameSTRINGTerminalRuleCall_6_0 = (RuleCall)cFileNameAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Photo:
		//	'Photo' photoTitle=STRING '{'
		//	'PhotoDescription' description=STRING
		//	'PhotoFileName' fileName=STRING
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Photo' photoTitle=STRING '{' 'PhotoDescription' description=STRING 'PhotoFileName' fileName=STRING '}'
		public Group getGroup() { return cGroup; }
		
		//'Photo'
		public Keyword getPhotoKeyword_0() { return cPhotoKeyword_0; }
		
		//photoTitle=STRING
		public Assignment getPhotoTitleAssignment_1() { return cPhotoTitleAssignment_1; }
		
		//STRING
		public RuleCall getPhotoTitleSTRINGTerminalRuleCall_1_0() { return cPhotoTitleSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'PhotoDescription'
		public Keyword getPhotoDescriptionKeyword_3() { return cPhotoDescriptionKeyword_3; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_0() { return cDescriptionSTRINGTerminalRuleCall_4_0; }
		
		//'PhotoFileName'
		public Keyword getPhotoFileNameKeyword_5() { return cPhotoFileNameKeyword_5; }
		
		//fileName=STRING
		public Assignment getFileNameAssignment_6() { return cFileNameAssignment_6; }
		
		//STRING
		public RuleCall getFileNameSTRINGTerminalRuleCall_6_0() { return cFileNameSTRINGTerminalRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final GenerateMeProgramElements pGenerateMeProgram;
	private final ConfigElements pConfig;
	private final HomePageElements pHomePage;
	private final PagesElements pPages;
	private final ContentPageElements pContentPage;
	private final ContactUsPageElements pContactUsPage;
	private final GalleryPageElements pGalleryPage;
	private final PhotoElements pPhoto;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GenerateMeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGenerateMeProgram = new GenerateMeProgramElements();
		this.pConfig = new ConfigElements();
		this.pHomePage = new HomePageElements();
		this.pPages = new PagesElements();
		this.pContentPage = new ContentPageElements();
		this.pContactUsPage = new ContactUsPageElements();
		this.pGalleryPage = new GalleryPageElements();
		this.pPhoto = new PhotoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uk.juliusz.generateme.GenerateMe".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//GenerateMeProgram:
	//	'BusinessName' businessName=STRING
	//	config=Config
	//	homePage=HomePage
	//	pages+=Pages*;
	public GenerateMeProgramElements getGenerateMeProgramAccess() {
		return pGenerateMeProgram;
	}
	
	public ParserRule getGenerateMeProgramRule() {
		return getGenerateMeProgramAccess().getRule();
	}
	
	//Config:
	//	'Sender' sender=STRING
	//	'Author' author=STRING;
	public ConfigElements getConfigAccess() {
		return pConfig;
	}
	
	public ParserRule getConfigRule() {
		return getConfigAccess().getRule();
	}
	
	//HomePage:
	//	'Introduction' Introduction=STRING;
	public HomePageElements getHomePageAccess() {
		return pHomePage;
	}
	
	public ParserRule getHomePageRule() {
		return getHomePageAccess().getRule();
	}
	
	//Pages:
	//	ContentPage | GalleryPage | ContactUsPage;
	public PagesElements getPagesAccess() {
		return pPages;
	}
	
	public ParserRule getPagesRule() {
		return getPagesAccess().getRule();
	}
	
	//ContentPage:
	//	'ContentPage' name=ID '{'
	//	'PageHeader' content=STRING
	//	'}';
	public ContentPageElements getContentPageAccess() {
		return pContentPage;
	}
	
	public ParserRule getContentPageRule() {
		return getContentPageAccess().getRule();
	}
	
	//ContactUsPage:
	//	'ContactUsPage' name=ID '{'
	//	'PageHeader' content=STRING
	//	'}';
	public ContactUsPageElements getContactUsPageAccess() {
		return pContactUsPage;
	}
	
	public ParserRule getContactUsPageRule() {
		return getContactUsPageAccess().getRule();
	}
	
	//GalleryPage:
	//	'GalleryPage' name=ID '{'
	//	photos+=Photo
	//	'}';
	public GalleryPageElements getGalleryPageAccess() {
		return pGalleryPage;
	}
	
	public ParserRule getGalleryPageRule() {
		return getGalleryPageAccess().getRule();
	}
	
	//Photo:
	//	'Photo' photoTitle=STRING '{'
	//	'PhotoDescription' description=STRING
	//	'PhotoFileName' fileName=STRING
	//	'}';
	public PhotoElements getPhotoAccess() {
		return pPhoto;
	}
	
	public ParserRule getPhotoRule() {
		return getPhotoAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
