/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContentPage#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContentPage()
 * @model
 * @generated
 */
public interface ContentPage extends Pages
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContentPage_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.ContentPage#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

} // ContentPage
