/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contact Us Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.ContactUsPage#getHeader <em>Header</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContactUsPage()
 * @model
 * @generated
 */
public interface ContactUsPage extends Pages
{
  /**
   * Returns the value of the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' attribute.
   * @see #setHeader(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getContactUsPage_Header()
   * @model
   * @generated
   */
  String getHeader();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.ContactUsPage#getHeader <em>Header</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' attribute.
   * @see #getHeader()
   * @generated
   */
  void setHeader(String value);

} // ContactUsPage
