/**
 * generated by Xtext 2.20.0
 */
package uk.juliusz.generateme.generateMe;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Home Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.juliusz.generateme.generateMe.HomePage#getIntroduction <em>Introduction</em>}</li>
 * </ul>
 *
 * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getHomePage()
 * @model
 * @generated
 */
public interface HomePage extends EObject
{
  /**
   * Returns the value of the '<em><b>Introduction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Introduction</em>' attribute.
   * @see #setIntroduction(String)
   * @see uk.juliusz.generateme.generateMe.GenerateMePackage#getHomePage_Introduction()
   * @model
   * @generated
   */
  String getIntroduction();

  /**
   * Sets the value of the '{@link uk.juliusz.generateme.generateMe.HomePage#getIntroduction <em>Introduction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Introduction</em>' attribute.
   * @see #getIntroduction()
   * @generated
   */
  void setIntroduction(String value);

} // HomePage
